### ISSUE TITLE
Permission denied rsync error

### ISSUE THREAD

**Issue by Boreas514** [eip-work/kuboard-spray#15]
TASK [download : download_file | Copy file from cache to nodes, if it is available] ***
fatal: [k8s-master]: FAILED! => {"attempts": 4, "changed": false, "cmd": "sshpass -d3 /usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o Port=22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L /data/resource/spray-v2.18.0a-2_k8s-v1.23.3_v1.6-amd64/content/kubespray_cache/kubeadm-v1.23.3-amd64 ********@192.168.0.201:/tmp/releases/kubeadm-v1.23.3-amd64", "msg": "Warning: Permanently added '192.168.0.201' (ECDSA) to the list of known hosts.\r\nrsync: mkstemp \"/tmp/releases/.kubeadm-v1.23.3-amd64.zcRU4K\" failed: Permission denied (13)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]\n", "rc": 23}

**Comment by Owenxh** [comment]
Does the problem resolve?
I got the same problem.

**Comment by Boreas514** [comment]
> Does the problem resolve? I got the same problem.

No, I've given up on the project.

**Comment by tonyjianhu** [comment]
I got the same problem too

**Comment by Boreas514** [comment]
> I got the same problem too

I've given up this project. Try to follow k8s official docs

**Comment by PonyTang3** [comment]
> Does the problem resolve? I got the same problem.

After I switched to root, I solved the problem

**Comment by shaohq** [comment]
请使用 root 用户
