### ISSUE TITLE
使用kuboard-spray安装服务器docker被卸载

### ISSUE THREAD

**Issue by cel105302** [eip-work/kuboard-spray#16]
当集群安装到图片位置时，日志自动断开，检查服务器docker，docker已被自动卸载![image](https://user-images.githubusercontent.com/32325588/154877013-ff43c8a5-a5dd-4b6e-8bbc-34769dd60dd5.png)

**Comment by shaohq** [comment]
kuboard-spray 所在机器不能用作集群的节点。
