### ISSUE TITLE
/bin/sh: 1: shyaml: not found

### ISSUE THREAD

**Issue by parzulpan** [eip-work/kuboard-spray#20]
fatal: [node1 -> localhost]: FAILED! => {
    "changed": true,
    "cmd": "cat package.yaml | shyaml get-value metadata.supported_os",
    "delta": "0:00:00.002894",
    "end": "2022-03-11 06:18:40.378894",
    "invocation": {
        "module_args": {
            "_raw_params": "cat package.yaml | shyaml get-value metadata.supported_os",
            "_uses_shell": true,
            "argv": null,
            "chdir": "/data/resource/spray-v2.18.0a-6_k8s-v1.23.4_v1.7-amd64/content",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 127,
    "start": "2022-03-11 06:18:40.376000",
    "stderr": "/bin/sh: 1: shyaml: not found",
    "stderr_lines": [
        "/bin/sh: 1: shyaml: not found"
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by shaohq** [comment]
请更新到最新的 kuboard-spray 版本
