### ISSUE TITLE
安装提示权限不足

### ISSUE THREAD

**Issue by tonyjianhu** [eip-work/kuboard-spray#21]
ubuntu 20.04 服务器 通过 kuoard Sapray部署k8s 群集，提示权限不足
首先 都是纯净服务器 均已安全docker 版本也过关
在网页上配置，在网页上配置，通过普通用户登录 然后选择 su切换到root身份，但是依然提示权限不足。具体错误描述如下

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/29139627/157845682-3b5ee3fd-127b-4098-8abd-a3ff1ed28200.png">

麻烦看看谢谢

**Comment by shaohq** [comment]
请直接配置 root 用户
