### ISSUE TITLE
日志总显示“已断开”，服务器上直接查看没有问题

### ISSUE THREAD

**Issue by DongyunLee** [eip-work/kuboard-spray#24]
![image](https://user-images.githubusercontent.com/22876282/159457933-c756a893-c4d4-4191-9a94-40e46044e738.png)

服务器上直接 `tail -F ` 是没问题的

F12 结果如下：
![image](https://user-images.githubusercontent.com/22876282/159458879-abc9c2fe-c2ea-4cd0-99da-b849153919d9.png)

**Comment by shaohq** [comment]
使用 chrome 浏览器
