### ISSUE TITLE
建议支持华为云的 Docker 镜像

### ISSUE THREAD

**Issue by DongyunLee** [eip-work/kuboard-spray#26]
新买了两天华为云的机器，用华为云的镜像应该会快一点吧？

参考：[华为云镜像站](https://mirrors.huaweicloud.com/home) -> [容器类] -> [Docker-CE]

**Comment by sprogFall** [comment]
实测在华为云上的docker还是用阿里云加速快

**Comment by shaohq** [comment]
现在的版本可以添加华为云镜像
