### ISSUE TITLE
kuboard-spray extra downloads

### ISSUE THREAD

**Issue by Gentvel** [eip-work/kuboard-spray#27]
Spray版本：v1.0.0-alpha.2-amd64
版本：spray-v2.18.0a-2_k8s-v1.23.3_v1.6-amd64
报错：
TASK [download : Add kuboard-spray extra downloads] ****************************
fatal: [Node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'kuboardspray_extra_downloads' is undefined\n\nThe error appears to be in '/data/resource/spray-v2.18.0a-2_k8s-v1.23.3_v1.6-amd64/content/3rd/kubespray/roles/download/tasks/main.yml': line 38, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: \"Add kuboard-spray extra downloads\"\n      ^ here\n"}
fatal: [Master]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'kuboardspray_extra_downloads' is undefined\n\nThe error appears to be in '/data/resource/spray-v2.18.0a-2_k8s-v1.23.3_v1.6-amd64/content/3rd/kubespray/roles/download/tasks/main.yml': line 38, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: \"Add kuboard-spray extra downloads\"\n      ^ here\n"}
fatal: [Node2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'kuboardspray_extra_downloads' is undefined\n\nThe error appears to be in '/data/resource/spray-v2.18.0a-2_k8s-v1.23.3_v1.6-amd64/content/3rd/kubespray/roles/download/tasks/main.yml': line 38, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: \"Add kuboard-spray extra downloads\"\n      ^ here\n"}

**Comment by Gentvel** [comment]
服务器版本：centos7.9

**Comment by shaohq** [comment]
请升级 kuboard-spray 到最新版本 v1.0.1
