### ISSUE TITLE
docker 启动无法映射为除80以外的其他端口

### ISSUE THREAD

**Issue by nian8** [eip-work/kuboard-spray#31]
docker run -d \
  --privileged \
  --restart=unless-stopped \
  --name=kuboard-spray \
  -p 2080:80/tcp \
  -e TZ=Asia/Shanghai \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/kuboard-spray-data:/data \
  eipwork/kuboard-spray:latest-amd64

**Comment by nian8** [comment]
映射端口改为 20080 可以启动。

**Comment by xuxueyun** [comment]
看看你本地端口是不是被占用了
