### ISSUE TITLE
在添加节点时，主机IP为172.168.52.62，绑定到 IP这项认为IP不是内网IP，无法进入下一步。

### ISSUE THREAD

**Issue by lhtzbj12** [eip-work/kuboard-spray#35]
在添加节点时，主机IP为172.168.52.62，绑定到 IP这项认为IP不是内网IP，无法进入下一步。

**Comment by lhtzbj12** [comment]
已经找到原因了。可能是我服务器IP段很奇葩。
// A类地址：10.0.0.0--10.255.255.255
// B类地址：172.16.0.0--172.31.255.255 
// C类地址：192.168.0.0--192.168.255.255
block = new Netmask('10.0.0.0/8')
if (block.contains(value)) {
  return callback()
}
block = new Netmask('172.16.0.0/12')
if (block.contains(value)) {
  return callback()
}
block = new Netmask('192.168.0.0/16') 
if (block.contains(value)) {
  return callback()
}
return callback('必须绑定到内网 IP')

**Comment by shaohq** [comment]
172.168.x.x 不是内网IP

**Comment by GodayMax** [comment]
请问咋解决？ 我这边的有一部分教育网机器内外网IP是一样的，无法更换IP，就卡住了
