### ISSUE TITLE
1.0.0 安装k8s集群后、添加不了子节点，提示证书失效、明明证书是我才生成的。

### ISSUE THREAD

**Issue by jiangximing** [eip-work/kuboard-spray#36]
![image](https://user-images.githubusercontent.com/42059769/167047501-5221db3b-be0b-43bc-b166-5b4afd63892e.png)
![Uploading image.png…]()
提示信息
fatal: [k8s-node1]: FAILED! => {"changed": true, "cmd": ["timeout", "-k", "120s", "120s", "/usr/local/bin/kubeadm", "join", "--config", "/etc/kubernetes/kubeadm-client.conf", "--ignore-preflight-errors=all", "--skip-phases="], "delta": "0:00:01.440080", "end": "2022-05-06 08:24:52.745365", "msg": "non-zero return code", "rc": 1, "start": "2022-05-06 08:24:51.305285", "stderr": "error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys \"sha256:59b9222cbe3f8be03512635847909f92988bdfd6a7104f66fe0d6d943defc8e3\" are pinned\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys \"sha256:59b9222cbe3f8be03512635847909f92988bdfd6a7104f66fe0d6d943defc8e3\" are pinned", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[preflight] Running pre-flight checks", "stdout_lines": ["[preflight] Running pre-flight checks"]}

**Comment by jiangximing** [comment]
k8s 主节点给出的生效token
![image](https://user-images.githubusercontent.com/42059769/167047632-b0c4215b-301b-43ac-86aa-5ff5bb103738.png)

**Comment by jiangximing** [comment]
手动执行报错的命令提示如下、error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys "sha256:59b9222cbe3f8be03512635847909f92988bdfd6a7104f66fe0d6d943defc8e3" are pinned

最关键的是提示的token 和我配置文件中的token 是不一样的
![image](https://user-images.githubusercontent.com/42059769/167047895-888b1d6c-4c7d-430f-8d60-e87f8736e62b.png)
![image](https://user-images.githubusercontent.com/42059769/167047972-49201c04-8ff2-49b5-aa56-1bd35a44f9f0.png)

**Comment by shaohq** [comment]
不能重现
