### ISSUE TITLE
v1.0.0-alpha 升级到 v1.1.0 后升级集群报错

### ISSUE THREAD

**Issue by a1403951401** [eip-work/kuboard-spray#37]
从 v1.0.0-alpha(spray-v2.18.5-5_k8s-v1.23.1_v1.4-amd64) 升级到 v1.1.0(spray-v2.18.0a-8_k8s-v1.23.6_v1.13-amd64) 

The task includes an option with an undefined variable. The error was: {'coredns': {'container': True, 'enabled': \"{{ dns_mode in ['coredns', 'coredns_dual'] }}\", 'groups': ['k8s_cluster'], 'repo': '{{ coredns_image_repo }}', 'sha256': '{{ coredns_digest_checksum|default(None) }}', 'tag': '{{ coredns_image_tag }}'}, 'kuboard': {'container': True, 'enabled': '{{ kuboard_enabled }}', 'file': False, 'groups': ['kube_control_plane'], 'repo': 'eipwork/kuboard', 'sha256': '', 'tag': '{{ kuboard_version }}', 'version': '{{ kuboard_version }}'}, 'netcheck_etcd': {'container': True, 'dest': '{{ local_release_dir }}/etcd-{{ netcheck_etcd_image_tag }}-linux-{{ image_arch }}.tar.gz', 'enabled': '{{ deploy_netchecker }}', 'file': False, 'groups': ['k8s_cluster'], 'mode': '0755', 'owner': 'root', 'repo': '{{ etcd_image_repo }}', 'sha256': '{{ etcd_digest_checksum|d(None) }}', 'tag': '{{ netcheck_etcd_image_tag }}', 'unarchive': False, 'version': '{{ netcheck_etcd_image_tag }}'}}: **'kuboard_enabled' is undefined**

The error appears to be in '/data/resource/spray-v2.18.0a-8_k8s-v1.23.6_v1.13
-amd64/content/3rd/kubespray/roles/download/tasks/main.yml': line 38, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  block:
    - name: \"Add kuboard-spray extra downloads\"
      ^ here

完整日志

[execute.log](https://github.com/eip-work/kuboard-spray/files/8644775/execute.log)

**Comment by youzainn** [comment]
似乎必须安装Kuboard可选组件才不报错

**Comment by shaohq** [comment]
此问题已在最新的资源包中解决

**Comment by Lin-qu** [comment]
spray-v2.19.0a_k8s-v1.24.3_v2.2-arm64 ARM版的也发现了这个问题哈

**Comment by fzf404** [comment]
我刚刚想升级来着，也碰到了。
