### ISSUE TITLE
为节点设置密码时，对带空格的密码支持不友好。

### ISSUE THREAD

**Issue by hmrg-grmh** [eip-work/kuboard-spray#6]
![image](https://user-images.githubusercontent.com/68635334/148513105-fc31e6f7-ef17-490b-b97b-a8b1003c6479.png)

位置：【集群管理】中新增集群，设置密码（不是密钥文件）时，在输入密码的框上：

- 顺序输入：敲击空格键，不能输入空格。
- 在中间输入：可以输入空格，但那个字符好像又不是空格（这也可能是 centos7 桌面的问题）。
- 复制密码粘贴：此方案可行。

----

就是说，如果密码里有空格，就需要编辑好再复制粘贴入此框，而不能直接输入。但我想其实有必要支持直接输入（顺序的）。

**Comment by shaohq** [comment]
将在 v1.0.0-alpha.3 中修订
