### ISSUE TITLE
各角色的证书不应该频繁更新，有效期建议默认设置为10年或100年

### ISSUE THREAD

**Issue by drummerglen** [eip-work/kuboard-spray#60]
证书不应该频繁更新，有效期建议默认设置为10年或100年
希望采纳

**Comment by 593769290** [comment]
调整controllerManager证书周期配置
roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
增加一行 
    experimental-cluster-signing-duration: 87600h
#######################################################
controllerManager:
  extraArgs:
    experimental-cluster-signing-duration: 87600h
