### ISSUE TITLE
ssh报错：Connection timed out

### ISSUE THREAD

**Issue by chengang2** [eip-work/kuboard-spray#84]
主机之间可以互相ssh。但是在添加节点的时候报错：Data could not be sent to remote host "xxx.xxx.xxx.xxx". Make sure this host can be reached over ssh: ssh: connect to host xxx.xxx.xxx.xxx  port 22: Connection timed out. 
kuboard-spray使用v1.2.4-amd64版本。

**Comment by hyq965672903** [comment]
你是啥情况啊 我这边遇到了同样问题
